require 'yaml'

workers_count = 2
masters_count = 1

starting_octet = 3

if starting_octet != 3
  raise "Keep the starting_octet at 3 to have the most usable IPs for the cluster. The DNS server is using 192.168.56.2. The rest is for the cluster nodes."
end

if masters_count.even? || masters_count < 1
  raise "Masters count must be an odd number greater than 0"
end

# load kubeone.yaml
config_file = File.join(File.dirname(__FILE__), "../kubeone/kubeone.yaml")
unless File.exist?(config_file)
  raise "Configuration file kubeone.yaml not found in ../kubeone directory"
end

yaml_data = YAML.load_file(config_file)
yaml_data["controlPlane"]["hosts"] = []
yaml_data["staticWorkers"]["hosts"] = []

Vagrant.configure("2") do |config|
  masters_count.times do |i|
    master_name = "master-#{i + 1}"
    master_config = {
      ip: "192.168.56.#{starting_octet + i}",
      cpus: 2,
      memory: 4096
    }

    yaml_data["controlPlane"]["hosts"].push(
      {
        "privateAddress" => master_config[:ip],
        "sshUsername" => "vagrant",
        "sshPrivateKeyFile" => "../vagrant/.vagrant/machines/#{master_name}/virtualbox/private_key",
        "taints" => [
          {
            "key" => "node-role.kubernetes.io/control-plane",
            "effect" => "NoSchedule"
          }
        ]
      }
    )

    if i == 0
      yaml_data["apiEndpoint"] = {
        "host" => master_config[:ip],
        "port" => 6443
      }
    end

    config.vm.define master_name do |master|
      master.vm.box = "bento/ubuntu-24.04"
      master.vm.box_version = "202510.26.0"
      master.vm.hostname = master_name
      master.vm.network "private_network", ip: master_config[:ip]
      master.vm.provider "virtualbox" do |vb|
        vb.cpus = master_config[:cpus]
        vb.memory = master_config[:memory]
      end
    end
  end

  workers_count.times do |i|
    worker_name = "worker-#{i + 1}"
    worker_config = {
      ip: "192.168.56.#{starting_octet + masters_count + i}",
      cpus: 2,
      memory: 4096
    }

    yaml_data["staticWorkers"]["hosts"].push(
      {
        "privateAddress" => worker_config[:ip],
        "sshUsername" => "vagrant",
        "sshPrivateKeyFile" => "../vagrant/.vagrant/machines/#{worker_name}/virtualbox/private_key"
      }
    )

    config.vm.define worker_name do |worker|
      worker.vm.box = "bento/ubuntu-24.04"
      worker.vm.box_version = "202510.26.0"
      worker.vm.hostname = worker_name
      worker.vm.network "private_network", ip: worker_config[:ip]
      worker.vm.provider "virtualbox" do |vb|
        vb.cpus = worker_config[:cpus]
        vb.memory = worker_config[:memory]
      end
    end
  end

  File.open(config_file, "w") do |file|
    file.write(yaml_data.to_yaml)
  end

  config.vm.define "dns-server" do |dns|
    dns.vm.box = "bento/ubuntu-24.04"
    dns.vm.box_version = "202510.26.0"
    dns.vm.hostname = "dns-server"
    dns.vm.network "private_network", ip: "192.168.56.2" # the 192.168.56.1 is reserved for the router
    dns.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end

    # Build dnsmasq config with worker IPs for round-robin
    dnsmasq_config = "# disable dns forwarding for .test domain\n"
    dnsmasq_config += "local=/test/\n"
    dnsmasq_config += "local-ttl=30\n"
    dnsmasq_config += "log-queries\n"
    dnsmasq_config += "log-facility=/var/log/dnsmasq.log\n"

    # Add worker addresses for round-robin DNS on *.app.test
    workers_count.times do |i|
      worker_ip = "192.168.56.#{starting_octet + masters_count + i}"
      dnsmasq_config += "address=/*.app.test/#{worker_ip}\n"
    end

    dns.vm.provision "shell", inline: <<-SHELL
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y dnsmasq
      cat <<EOF > /etc/dnsmasq.d/k8s.conf
#{dnsmasq_config}
EOF
      # the systemd-resolved was using port 53 therefore the dnsmasq couldn't start
      systemctl stop systemd-resolved
      # the /etc/resolv.conf now has to point to 126.0.0.1
      sed -i 's/nameserver 127.0.0.53/nameserver 127.0.0.1/' /etc/resolv.conf
      systemctl restart dnsmasq
      systemctl enable dnsmasq
      systemctl status dnsmasq --no-pager
    SHELL
  end
end
